### PR TITLE
change message event to confirm with recent changes

### PR DESCRIPTION
**Pull request by jelly972**
change the event to match the current spec 

https://w3c.github.io/ServiceWorker/#extendablemessage-event-data

### CODE REVIEW

**Comment by zackargyle** [comment]
Looks great! Thanks for the submission!

**Comment by kontrollanten** [comment]
Shouldn't this be considered as a breaking change since it completely changes how to trigger events?

```
self.trigger('message', Object.assign(new Event(), { data: 'skipWaiting' }));
```

No longer works and instead needs to be

```
self.trigger('message', 'skipWaiting');
```

**Comment by zackargyle** [comment]
This should not affect how the event was triggered. Previously, the second argument for MessageEvent was completely unused, so the first example did not actually do anything previously.

**Comment by kontrollanten** [comment]
Are you sure?

Previously it was:

```
constructor(type, args) {
  super()
  Object.assign(this, args);
}
```

Which would run `Object.assign(this, Object.assign(new Event(), { data: 'skipWaiting' })` with my example. And the result should've been that `this.data` had value `skipWaiting`?

Anyway, not a big deal. Thanks for a great module to make it easier write tests.

**Comment by zackargyle** [comment]
Oh gosh, thank you! This pull request is actually wrong according to: [MessageEvent](https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent/MessageEvent). The init object should contain `data` not be the data. I'm going to revert.

**Comment by zackargyle** [comment]
Reverted and updated to be more explicit according to the spec. Live in 1.10.1

**Pull request merged**
