### PR TITLE
fix: Support new scope option

### PR DESCRIPTION
**Pull request by jcreamer898**
I'm having an issue with this plugin because of the way you register the service worker against the `publicPath` from WebPack...

In our case, we have the following in `output`...

```js
output: {
  path: path.join(__dirname, "public", "assets"),
  filename: "[name].js",
  chunkFilename: "[name]_[chunkhash:20].js",
  publicPath: `/assets/`,
  libraryTarget: "var",
}
```

Since the `generateRuntime` file uses the `publicPath`, https://github.com/pinterest/service-workers/blob/master/packages/service-worker-plugin/utils/generateRuntime.js#L15, the "scope" of the service worker is incorrectly getting set to `http://localhost:3000/assets/` and isn't firing correctly.

I tried to pass `publicPath: "/"` directly into the options for this plugin, but that messed up the `precache` assets because they were getting set as `["/foo.fs"]` instead of `["/assets/foo.js"]`.

The only way I could figure out how to do this was to pass in the following config...

```js
{
  publicPath: "/assets/",
  writePath: path.join(process.cwd(), "public"),
  scope: "/",
  cache: {
    offline: true,
    precache: ["\\.js", "\\.css"],
    strategy: [{
      type: "prefer-cache",
      matches: ["\\.js", "\\.css"],
    }],
  },
}
```

This correctly sets up the service worker at `localhost:3000/sw-main.js` whilst still adding the correct cached paths into the generated service worker.

According to Google...

> One subtlety with the register() method is the location of the service worker file. You'll notice in this case that the service worker file is at the root of the domain. This means that the service worker's scope will be the entire origin. In other words, this service worker will receive fetch events for everything on this domain. If we register the service worker file at /example/sw.js, then the service worker would only see fetch events for pages whose URL starts with /example/ (i.e. /example/page1/, /example/page2/).

https://developers.google.com/web/fundamentals/primers/service-workers/#register_a_service_worker

### CODE REVIEW

**Comment by zackargyle** [comment]
Hi Jonathan! Thanks for the PR and we definitely want to figure out a fix for you. To help me understand a little better I wanted to verify a few of your configurations.

You want your service workers to be served from `.com/sw-{key}.js`, but generateRuntime thinks they are at `.com/assets/sw-{key}.js` because of your public path. Your write path is `<root>/public`.

It seems like I may have a bug here in assuming publicPath should be used for the runtime prefixing. I like the idea of this `scope`. Can we rename it to `runtimePath`? I think that would be a little more explicit about it's purpose. There is a place we're writing files to (writePath), a place we're reading from (webpack publicPath), and a place we care about for runtime prefixes (runtimePath).

Renaming sound good to you?

**Comment by jcreamer898** [comment]
Sound great!

**Comment by zackargyle** [comment]
Thank you! I'll merge and add the new option to the README.

**Comment by jcreamer898** [comment]
Awesome, glad to help out. :) Thanks for putting this together. Made spinning up a service worker way easier for us.

**Pull request merged**
